FROM docker.io/archlinux:latest

# Update
RUN set -ex && \
    pacman -Syu --noconfirm

# Install packages
RUN set -ex && \
    pacman -S --noconfirm \
              base-devel openssh git vim qt5 qt6 qtcreator cmake \
              ninja gdb qt5ct qt6ct repo extra-cmake-modules \
              polkit-qt5 solid libdrm libinput xcb-util-cursor \
              pulseaudio networkmanager-qt modemmanager-qt glib2 \
              dconf pipewire libxkbcommon flatpak appstream-qt \
              wayland pam umockdev dos2unix \
              ttf-fira-code ttf-fira-mono ttf-fira-sans

RUN set -ex && \
    sudo ln -s /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open && \
    sudo ln -s /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree
